apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: increasing-pelican-dotnet-basic 
  janus-idp.io/tekton: increasing-pelican-dotnet-basic
  backstage.io/kubernetes-id: increasing-pelican-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: increasing-pelican-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  