apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: increasing-pelican-dotnet-basic
  janus-idp.io/tekton: increasing-pelican-dotnet-basic
  backstage.io/kubernetes-id: increasing-pelican-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: increasing-pelican-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
