apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: increasing-pelican-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-hub/increasing-pelican-dotnet-basic